In [53]:
import torch
import numpy as np

In [54]:
# Создайте случайный FloatTensor размера 3x4x5

In [68]:
a = torch.randn(3, 4, 5).float()

In [69]:
# Выведите его форму (shape)

In [70]:
a.size()

torch.Size([3, 4, 5])

In [71]:
# Приведите его к форме 6 X 10

In [72]:
a.resize_(6,10)

tensor([[-1.8169,  0.6535,  0.4798, -0.6707,  0.2921, -0.1369,  0.6260,  0.7072,
         -1.3895, -0.5799],
        [-0.3704, -0.3040,  1.7682,  0.8901, -0.3233,  0.8426, -0.1254, -0.4894,
         -0.2940,  0.7327],
        [-0.8307, -0.3966,  0.1361,  0.9658,  0.9830,  0.6826,  0.7238,  0.0802,
         -0.6743, -0.0943],
        [-0.0583,  1.6298, -1.0830,  1.2182,  1.4405,  0.9142,  0.4904,  0.1840,
         -0.6713,  0.8119],
        [ 1.4347, -1.1321, -0.1936,  1.2694, -0.3317,  0.2266, -0.0104,  1.5918,
         -0.7801,  0.0715],
        [-0.1645,  0.1095, -0.1725,  1.8692, -0.1640,  0.3115,  0.5938,  0.4384,
         -0.0757,  1.0128]])

In [60]:
a.size()

torch.Size([6, 10])

In [38]:
# Создайте случайный IntTensor размера 10

In [74]:
b = torch.randint(10, size=(10, 1)).type(torch.IntTensor)

In [75]:
b.size()

torch.Size([10, 1])

In [6]:
# Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [77]:
c = a * b.T

In [79]:
c.size()

torch.Size([6, 10])

In [80]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [81]:
d = c @ c.T

In [83]:
d.size()

torch.Size([6, 6])

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [84]:
x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)


y = x**3 + z - 75 * t

y.backward()
x.grad, z.grad, t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [8]:
# Создайте единичный тензор размера 5x6

In [85]:
e = torch.ones(5, 6)

In [9]:
# Переведите его в формат numpy

In [87]:
e = e.numpy()

In [88]:
e

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)